// <auto-generated />
namespace Jeylabs.AJG.PickeringsForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TimeOFEvent_LengthChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TimeOFEvent_LengthChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201704111111360_TimeOFEvent_LengthChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
