// <auto-generated />
namespace Jeylabs.AJG.PickeringsForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class length_registration_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(length_registration_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201703281917450_length_registration_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
